name: Initialize

description: >
  Copies the PowerShell modules to a location defined in PSModulePath (since GHA doesn't allow manipulating
  environment variables) and also installs and imports them.

runs:
  using: "composite"
  steps:
    - name: Copy Modules
      shell: pwsh
      run: |
        $sourcePath = (Resolve-Path "${{ github.action_path }}/../../..").Path
        $destinationPath = ($env:PSModulePath -split [IO.Path]::PathSeparator)[0]
        foreach ($modulePath in (Get-ChildItem $sourcePath -Recurse -Include "*.psm1"))
        {
          New-Item -ItemType Directory -Path $destinationPath -Name $modulePath.Directory.Name
          Copy-Item $modulePath -Destination (Join-Path -Path $destinationPath -ChildPath $modulePath.Directory.Name)
        }

    - name: Install and Import Modules
      shell: pwsh
      run: |
        foreach ($moduleName in (Get-ChildItem -Directory | select Name))
        {
          if (Test-Path -Path $moduleName/$moduleName.psm1)
          {
            Import-Module $moduleName.Name
          }
        }
