name: Check Spelling

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  check-spelling:
    name: Check Spelling
    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@issue/OSOE-523
    with:
      additional-dictionaries: |
        lombiq-lgha:Lombiq.common.txt
